### ISSUE TITLE
UI 만들기

### ISSUE THREAD

**Issue by seunghyunyay** [seunghyunyay/priceyay#7]
## 설명
UI 구현하기

## TODO 
- [ ] TopAppBar
- [ ] HomeScreen
  - [ ] 최근 방문한 식당 
  - [ ] 카테고리
  - [ ] 착한 가격 업소란
- [ ] SearchScreen
  - [ ] 검색 바
- [ ] BookmarkScreen
  - [ ] 그리드 화면 구현
- [ ] SeachResultScreen
  - [ ] 검색 결과 화면
- [ ] 착한 가격 업소 정보 화면
- [ ] 네이버 맵 화면
